apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - mysql-init-configmap.yaml
  - mysql-deployment.yaml
  - auth-service-deployment.yaml
  - api-gateway-deployment.yaml
  - frontend-deployment.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: tourist-agency
  app.kubernetes.io/version: "1.0.0"